name: scannie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 카메라
  camera: ^0.11.0+2

  # 문서 테두리 자동 인식
  edge_detection: ^1.1.1

  # 이미지 처리
  image: ^4.1.7
  image_cropper: ^5.0.1

  # PDF 생성
  pdf: ^3.11.1
  printing: ^5.12.0

  # 파일 저장
  path_provider: ^2.1.3

  # 권한
  permission_handler: ^11.3.1

  # 상태 관리
  provider: ^6.1.2

  # 로컬 저장
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
