name: scannie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  permission_handler: ^12.0.1
  path_provider: ^2.0.11
  path: ^1.8.2
  cunning_document_scanner_plus: ^1.0.3
  ffi: ^2.1.0
  reorderable_grid_view: ^2.2.8
  pdf: ^3.11.1
  printing: ^5.13.4
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
