name: scannie
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+48

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  path: ^1.8.2
  permission_handler: ^12.0.1
  flutter_reorderable_grid_view: ^5.4.0
  pdf: ^3.11.1
  printing: ^5.13.4
  shared_preferences: ^2.2.2
  image_gallery_saver_plus: ^4.0.1
  share_plus: ^12.0.1
  file_saver: ^0.3.1
  image_picker: ^1.1.2
  flutter_pdfview: ^1.3.2
  pdfx: ^2.6.0
  file_picker: ^10.3.7
  shadcn_ui: ^0.40.2
  toastification: ^3.0.3
  wolt_modal_sheet: ^0.11.0
  google_fonts: ^6.3.3
  flutter_image_compress: ^2.4.0
  pro_image_editor: 11.6.0-beta.1
  cunning_document_scanner_plus: ^1.0.3
  archive: ^4.0.0
  flutter_neumorphic_plus: ^3.5.0
  easy_localization: ^3.0.7
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6
  uuid: ^4.5.2
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: ^0.4.6  # iOS-specific features (SKPaymentQueueWrapper)
  package_info_plus: ^9.0.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#7DD3C0"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0F172A"
  image: assets/splash_icon.png
  fullscreen: false

  android_12:
    color: "#FFFFFF"
    color_dark: "#0F172A"
    image: assets/splash_icon.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#0F172A"

flutter:
  uses-material-design: true
  # shaders:
  #   - packages/pro_image_editor/lib/shared/shaders/pixelate.frag
  assets:
    - assets/translations/
