name: scannie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
