name: scannie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  path: ^1.8.2
  cunning_document_scanner_plus: ^1.0.3
  reorderable_grid_view: ^2.2.8
  pdf: ^3.11.1
  printing: ^5.13.4
  shared_preferences: ^2.2.2
  open_file_manager: ^2.0.1
  media_store_plus: ^0.1.3
  image_gallery_saver_plus: ^4.0.1
  share_plus: ^12.0.1
  image_picker: ^1.1.2
  flutter_pdfview: ^1.3.2
  shadcn_ui: ^0.39.7
  elegant_notification: ^2.5.1
  ndialog: ^4.5.0+1
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.4.0
  archive: ^3.6.1
  flutter_neumorphic_plus: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
