name: scannie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  path: ^1.8.2
  cunning_document_scanner_plus: ^1.0.3
  reorderable_grid_view: ^2.2.8
  pdf: ^3.11.1
  printing: ^5.13.4
  shared_preferences: ^2.2.2
  open_file_manager: ^2.0.1
  media_store_plus: ^0.1.3
  image_gallery_saver_plus: ^4.0.1
  share_plus: ^12.0.1
  image_picker: ^1.1.2
  flutter_pdfview: ^1.3.2
  shadcn_ui: ^0.39.10
  elegant_notification: ^2.5.1
  ndialog: ^4.5.0+1
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.4.0
  image_cropper: ^11.0.0
  archive: ^4.0.0
  flutter_neumorphic_plus: ^3.5.0
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon.png
  fullscreen: false

  android_12:
    color: "#FFFFFF"
    image: assets/app_icon.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
